name: Python tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          # The amount of valid python, spark, hadoop combinations is almost endless so we just focus on the LTS and new Databricks Runtime releases
          # https://docs.databricks.com/en/release-notes/runtime/index.html

          # Lowest version allowed by setup.py and requirements.txt
          - python: '3.7'
            spark: '3.1.1'
            hadoop: '2.7'
          # DBR 9.1 LTS
          - python: '3.8'
            spark: '3.1.2'
            hadoop: '2.7'
          # DBR 10.4 LTS
          - python: '3.8'
            spark: '3.2.1'
            hadoop: '3.2'
          # DBR 11.3 LTS
          - python: '3.9'
            spark: '3.3.0'
            hadoop: '3'
          # DBR 12.2 LTS
          - python: '3.9'
            spark: '3.3.2'
            hadoop: '3'
          # DBR 13.3 LTS
          - python: '3.10'
            spark: '3.4.1'
            hadoop: '3'
          # DBR 14.2
          - python: '3.10'
            spark: '3.5.0'
            hadoop: '3'
          # Newer python versions which are not in DBR's yet
          # (Python 3.12 is not supported on Spark 3.5.0)
          - python: '3.11'
            spark: '3.5.0'
            hadoop: '3'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.versions.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.versions.python }}
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    - uses: vemonet/setup-spark@v1
      with:
        spark-version: ${{ matrix.versions.spark }}
        hadoop-version: ${{ matrix.versions.hadoop }}
    - name: Install pip
      run: python -m pip install --upgrade pip
    - name: Install wheel
      run: pip install wheel
    - name: Install flake8
      run: python -m pip install flake8 pytest
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg,*.sql,venv
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg,*.sql,venv
    - name: Test with pytest
      run: |
        python -m pytest tests/
    - name: Install
      run: |
        python setup.py sdist bdist_wheel
        pip install dist/pyspark_nested_functions-*.whl